### ISSUE TITLE
Get calender events of next exams

### ISSUE THREAD

**Issue by spoonerWeb** [JonasJoKuJonas/homeassistant-WebUntis#100]
In WebUntis you also can see if there are exams during a lesson.
It would be nice to have a list of next exams with date, time, lesson and description.

**Comment by dprinz** [comment]
with python-webuntis it seems to be possible to get a list of exam_types and exams. This could be feeded into a new calendar entity.

**Comment by cofw2005** [comment]
This is a good request! I like to have that feature too :)

**Comment by JonasJoKuJonas** [comment]
added in v1.3.0

**Comment by dprinz** [comment]
Great, thank you a lot!

**Comment by cofw2005** [comment]
Great! just had freshly tested with the new version. seems my exam calendar didn't show up the exams which I can see in Untis. basically in my exam calendar, it is empty. Is it only on me?
but the homework calendar does work!

**Comment by spoonerWeb** [comment]
Same for me. Calendar is existing but without content. Homework calendar works.

**Comment by JonasJoKuJonas** [comment]
continue discussion in #160
