### ISSUE TITLE
Webuntis fails to accept server

### ISSUE THREAD

**Issue by deepblue120** [JonasJoKuJonas/homeassistant-WebUntis#102]
### The problem

I am trying to install the webuntis but it does not accept the server. The server is ajax.webuntis.com

### Version of Home Assistant?

Core 2024.1.2 Supervisor 2023.12.0 Operating System 11.3 Frontend 20240104.0

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v1.03

**Comment by JonasJoKuJonas** [comment]
What does the error say? Have you found any additional logs in the Home Assistant logs page?

**Comment by JonasJoKuJonas** [comment]
Is it working now?
The WebUntis server was down for a few hours.
It's working again for me

**Comment by deepblue120** [comment]
Works perfectly now for me. Thanks a lot. Really nice.
