### ISSUE TITLE
student not found

### ISSUE THREAD

**Issue by deepblue120** [JonasJoKuJonas/homeassistant-WebUntis#103]
### The problem

Trying to add a new student. Error with "student not found". Log in on webuntis.com is working though. When I type a wrong password on purpose it says wrong username and/or password. So I guess the connection is working.

### Version of Home Assistant?

11.4

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v1.04

### Traceback/Error logs

No log entry for the error message: student not found.

**Comment by JonasJoKuJonas** [comment]
Try entering the name in different ways, such as "First_name, Last_name" or "Last_name, First_name." Normally, the name displayed on the WebUntis app should work. 
If that doesn't resolve the issue, attempt to add the timetable by class, as described here:
https://github.com/JonasJoKuJonas/homeassistant-WebUntis/issues/92#issuecomment-1791731970

**Comment by deepblue120** [comment]
Thank you Jonas. Works fine. Two kids on the same school but different settings. Weird.
