### ISSUE TITLE
invalid school name/id for school with spaces in the name

### ISSUE THREAD

**Issue by Kurty00** [JonasJoKuJonas/homeassistant-WebUntis#104]
### The problem

The school name my school includes a space. This causes the setup to give me an "invalid school name/id" error, even if I escape the space with a + like the loginpage does.

### Version of Home Assistant?

2024.1.3

### What type of installation are you running?

Home Assistant Container

### Version of WebUntis

unknown

### Traceback/Error logs

2024-01-15 11:50:43.954 ERROR (MainThread) [frontend.js.latest.202401040] Uncaught error from Firefox 122.0 on Windows 10
TypeError: can't access property "domain", i is undefined
integration (src/panels/config/integrations/dialog-add-integration.ts:464:4)
item (src/virtualize.ts:116:53)
r (src/directives/repeat.ts:56:28)
ct (src/directives/repeat.ts:93:52)
update (src/directive.ts:134:16)
_$AS (src/lit-html.ts:1085:23)
S (src/lit-html.ts:1362:12)
_$AI (src/async-directive.ts:366:18)
setValue (src/virtualize.ts:139:13)
dispatchEvent (src/Virtualizer.ts:808:23)

### Additional information

mese.webuntis.com

**Comment by JonasJoKuJonas** [comment]
This looks like a browser issue to me. Have you tried to set up the integration from a different device or browser?

**Comment by Kurty00** [comment]
Tried around a bit more. Turns out I had to urlencode the school name, so using '%20' as an escape sequence.
