### ISSUE TITLE
Custom Sensor Change Output

### ISSUE THREAD

**Issue by duckplayz** [JonasJoKuJonas/homeassistant-WebUntis#105]
Hello,
I am pretty new with home assistant and i ran into a problem.

I want to create an Alarm based on the time of the first lesson. For this im using the Sensor template provided in the readme.
However the state of the custom sensor is for example "2024-01-31 06:30:00+01:00". 
I simply want it to be 6:30:00 so i can easily integrate it into a automation. So the sensor should just output for example "6:30:00" or "9:50:00".
Is there a way to change that in the Sensor Template?

**This is the current state.**

```
- platform: template
  sensors:
    webuntis_wake_up_time:
      entity_id: sensor.webuntis_wakeup_time
      friendly_name: "WebUntis Wake up Time"
      value_template: >
          {% set datetime = states('sensor.MYNAME_next_lesson_to_wake_up') %}
          {% if datetime not in ["unknown", "unavailable", None] %}
            {% set datetime = datetime | as_datetime | as_local %}
            {% set time = datetime.hour|string + ":" + datetime.minute|string %}
              
              
              
            {% if time == "7:55" %}
              {% set weak_up_time = "6:30" %}
            {% elif time == "8:45" %}
              {% set weak_up_time = "7:30" %}
            {% elif time == "9:50" %}
              {% set weak_up_time = "8:15" %}
            {% endif %}
              
            {{ datetime.replace(hour=weak_up_time.split(":")[0]|int, minute=weak_up_time.split(":")[1]|int) }}
          {% else %}
            {{ None }}
          {% endif %}
```

**Comment by JonasJoKuJonas** [comment]
You can use sth like this to trigger the automation
```
platform: template
value_template: >-
  {{ 0 < as_timestamp(now()) - as_timestamp(states("sensor.webuntis_wake_up_time") | as_datetime | as_local) < 60 }}

```

**Comment by duckplayz** [comment]
I simply want to be able to use it in the UI automation creation because I don't really Unterstand the yaml thing. I also einst to use it for some further automations. 
Isn't there any way to change the sensor yaml so it only shows "6:00:00"?

**Comment by duckplayz** [comment]
So if i use this as a trigger for an automation it will trigger the autmation at the specified time in the sensor template?
So if my school starts tomorrow at 7:55 the automation will trigger if its 6:30? Or what do i need to do for that?
Sorry if im asking stupid questions but i dont really know much about the yaml thing.

**Comment by JonasJoKuJonas** [comment]
Exactly, the automation will trigger at 6:30

**Comment by duckplayz** [comment]
Okay i configured it now and lets hope it works. I simply setup a notification for my phone so i can test if the automation works tomorrow at 6:30!

**Comment by duckplayz** [comment]
Hello again,
It has worked fine today so
Thanks for the help!
