### ISSUE TITLE
Notification for scheduler changes

### ISSUE THREAD

**Issue by Winkenbm** [JonasJoKuJonas/homeassistant-WebUntis#106]
It would be great if it would be possible to send notifications for changes in the scheduler (change of rooms/teacher, canceled lessons)
Thanks for your work!

**Comment by JonasJoKuJonas** [comment]
Do you mean sending notifications via a notify service? If yes this is already a feature and can be set up in the option Flow

**Comment by zavjah** [comment]
HI there, I'd like to set up notifications, preferably an automation to trigger it at evening or similar, for cancelled lessons but only for the next day. The notif service via the option flow notifs of all cancellation and most are far in the future at our school. Is there a way to use calendar entity or something. Is something like this possible?
