### ISSUE TITLE
No output after clicking "submit" in the configurator UI

### ISSUE THREAD

**Issue by Racer0412** [JonasJoKuJonas/homeassistant-WebUntis#109]
### The problem

After clicking on submit I don't get any further. Seems like there is an issue from my schools side. Even though everyone got personal accounts I can't add it to HA. I'm just wondering what the Problem could be since I'm not even getting an error in the UI configurator.
If you need further details let me know :)

### Version of Home Assistant?

Core 2024.2.5 Supervisor 2024.02.1 Operating System 11.4 Frontend 20240207.1

### What type of installation are you running?

Home Assistant Core

### Version of WebUntis

v1.06

**Comment by JonasJoKuJonas** [comment]
Do you get anything in the home assistant logs?

**Comment by Racer0412** [comment]
Logger: webuntis
Source: /usr/local/lib/python3.12/site-packages/webuntis/utils/logger.py:19
First occurred: 21:49:11 (26 occurrences)
Last logged: 21:59:10

{'jsonrpc': '2.0', 'id': '2024-03-03 21:57:19.686264', 'error': {'message': 'bad credentials', 'code': -8504}}
{'jsonrpc': '2.0', 'id': '2024-03-03 21:59:08.231613', 'error': {'message': 'bad credentials', 'code': -8504}}
{'jsonrpc': '2.0', 'id': '2024-03-03 21:59:09.064979', 'error': {'message': 'bad credentials', 'code': -8504}}
{'jsonrpc': '2.0', 'id': '2024-03-03 21:59:09.645925', 'error': {'message': 'bad credentials', 'code': -8504}}
{'jsonrpc': '2.0', 'id': '2024-03-03 21:59:10.217675', 'error': {'message': 'bad credentials', 'code': -8504}}

and

This error originated from a custom integration.

Logger: custom_components.webuntis.config_flow
Source: custom_components/webuntis/config_flow.py:54
Integration: webuntis (documentation, issues)
First occurred: 21:57:13 (1 occurrences)
Last logged: 21:57:13

Cannot resolve hostname: [Errno -2] Name does not resolve

**Comment by JonasJoKuJonas** [comment]
{'jsonrpc': '2.0', 'id': '2024-03-03 21:57:19.686264', 'error': {'message': 'bad credentials', 'code': -8504}}
this error suggests that sth is wrong with the password. Do you have a password with special special characters like "ÄÜß"?

**Comment by Racer0412** [comment]
Nope I don't have special characters in my pw.

**Comment by JonasJoKuJonas** [comment]
Try again in a few hours, this sometimes fixes the "Bad Credentials" error

**Comment by Racer0412** [comment]
Could characters like space cause this issue?

**Comment by Racer0412** [comment]
Somehow fixed itself after a few retries. Thanks a lot for the quick response and for setting up this whole integration!

BR
