### ISSUE TITLE
Kalender ist 1 Stunde versetzt.

### ISSUE THREAD

**Issue by CyberLine** [JonasJoKuJonas/homeassistant-WebUntis#110]
### The problem

Alle Zeiten im Kalender sind immer eine Stunde hinterher. Aber auch nur dieser Kalender von WebUntis. Hostzeit etc. passt.
Ich habe auch nichts gefunden das anzupassen. In der normalen Untis App passen die Zeiten.

### Version of Home Assistant?

2024.2.5

### What type of installation are you running?

Home Assistant Container

### Version of WebUntis

0.1.22

**Comment by JonasJoKuJonas** [comment]
Do you still have this issue?

**Comment by mtdcr** [comment]
FWIW, not OP, but I fixed this problem for me by mounting /etc/localtime from the host into the container and/or setting the TZ environment variable (can't look right now, but I think it was the former).

**Comment by JonasJoKuJonas** [comment]
As described here?
https://github.com/JonasJoKuJonas/homeassistant-WebUntis?tab=readme-ov-file#docker

If it works now, you may close the issue

**Comment by JonasJoKuJonas** [comment]
There hasn't been any recent activity on this issue. I will now close it. If it's still not working, please reopen it and provide further information so that I can assist you.

Thank you for your contributions.
