### ISSUE TITLE
Setup funktioniert nicht 

### ISSUE THREAD

**Issue by tamay-idk** [JonasJoKuJonas/homeassistant-WebUntis#118]
### The problem

Ich habe in Home Assistant nach dem hinzufügen von der WebUntis Integration alles was nötig ist eingetragen, aber wenn ich weiter klicke, passiert nichts. Kein Fehler, sondern nichts. 

### Version of Home Assistant?

12.2

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

2024.11.1

### Additional information

Vielleicht trage ich das allerletzte mit Name/Class/Lesson/Room (oder wie auch immer das war, auf jeden Fall so ähnlich) falsch ein, weil ich ja keine Ahnung hab was ich bei Lesson eintragen soll. Aber ein Fehler kommt auch nicht.

**Comment by JonasJoKuJonas** [comment]
Eigentlich solltest du ein Fehler bekomme. Schau auch mal in die [HA logs](https://my.home-assistant.io/redirect/logs/?)Versuche es mal mit einem anderen Browser oder Gerät.

**Comment by JonasJoKuJonas** [comment]
Eigentlich solltest du ein Fehler bekomme. Schau auch mal in die [HA logs](https://my.home-assistant.io/redirect/logs/?).
Versuche es mal mit einem anderen Browser oder Gerät. 
Einrichtung nach folgenden schritten [README](https://github.com/JonasJoKuJonas/homeassistant-WebUntis?tab=readme-ov-file#timetable-source--full-name-class-subject-room)

**Comment by tamay-idk** [comment]
Hier sind die logs dazu: 
logger:%20webuntis%0AQuelle%3A%20/usr/local/lib/python3.12/site-packages/webuntis/utils/logger.py:19%0AErstmals%20aufgetreten:%2012:43:04%20(2%20Vorkommnisse)%0AZuletzt%20protokolliert:%2012:43:06%0A%0A%7B'jsonrpc':%20'2.0',%20'id':%20'2024-04-19%2012:43:04.228210',%20'error':%20%7B'message':%20'bad%20credentials',%20'code':%20-8504%7D%7D%0A%7B'jsonrpc':%20'2.0',%20'id':%20'2024-04-19%2012:43:06.577298',%20'error':%20%7B'message':%20'bad%20credentials',%20'code':%20-8504%7D%7D

Ich versuche das selbe schon seit 2 Tagen und habe mit mehreren Geräten versucht.

**Comment by JonasJoKuJonas** [comment]
duplicate of #109 
here it fixed itself after a few days so just try setting up again
