### ISSUE TITLE
Migrationsfehler seit letztem Update auf v1.1.1

### ISSUE THREAD

**Issue by deepblue120** [JonasJoKuJonas/homeassistant-WebUntis#122]
### The problem

Meine beiden Einträge haben seit dem letzten Update einen Migrationsfehler. 

### Version of Home Assistant?

Core 2024.5.2 Supervisor 2024.04.4 Operating System 12.2 Frontend 20240501.1

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v1.1.1

**Comment by deepblue120** [comment]
Aus den Protokollen kommt folgendes:
Logger: homeassistant.config_entries
Quelle: config_entries.py:880
Erstmals aufgetreten: 07:27:19 (2 Vorkommnisse)
Zuletzt protokolliert: 07:27:19

Error migrating entry sohn for webuntis
Error migrating entry tochter for webuntis
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 880, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/__init__.py", line 98, in async_migrate_entry
    options["notify_config"][notify_key]["options"].index("lesson change")
ValueError: 'lesson change' is not in list

**Comment by JonasJoKuJonas** [comment]
quick fix - should work now

**Comment by deepblue120** [comment]
Still doesn´t work? Restartet HA.

**Comment by JonasJoKuJonas** [comment]
do you get the same error?

**Comment by deepblue120** [comment]
Yes

**Comment by JonasJoKuJonas** [comment]
schick nochmal den neuen error

**Comment by JonasJoKuJonas** [comment]
Du kannst auch auf Discord schreiben
da bekommst du meist schneller eine Antwort

**Comment by deepblue120** [comment]
Hab ich (noch) nicht. Hier der Fehler

Logger: homeassistant.config_entries
Quelle: config_entries.py:880
Erstmals aufgetreten: 09:23:58 (2 Vorkommnisse)
Zuletzt protokolliert: 09:23:58

Error migrating entry Tochter for webuntis
Error migrating entry Sohn for webuntis
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 880, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/__init__.py", line 98, in async_migrate_entry
    options["notify_config"][notify_key]["options"].index("lesson change")
ValueError: 'lesson change' is not in list

**Comment by JonasJoKuJonas** [comment]
Der Fehler ist noch von der alten Version.
Da ist beim aktualisieren irgendwas schief gelaufen

**Comment by deepblue120** [comment]
Hallo Jonas,
ich habe keine Aktualisierung in HA. Es sieht so aus als wäre v1.1.1 immer noch die aktuellste Version. Kann ich auch manuell updaten?

**Comment by deepblue120** [comment]
Kommando zurück. Als Beta Update ist v1.1.2 vorhanden. Werde ich sofort testen.

**Comment by deepblue120** [comment]
Egal. Funktioniert wieder wie es soll. Vielen Dank an Dich für Deine schnelle Hilfe.
