### ISSUE TITLE
Discord Channel geht nicht?

### ISSUE THREAD

**Issue by mcpdev80** [JonasJoKuJonas/homeassistant-WebUntis#123]
Moin Moin,

ich wollte mehr Beispiele haben, da ich nicht weiß, was ich hier eintragen soll:

Full Name/ Class/ Subject/ Room

Aber leider geht der Discord link nicht.

**Comment by JonasJoKuJonas** [comment]
> ich wollte mehr Beispiele haben, da ich nicht weiß, was ich hier eintragen soll

je nach dem was du vorher ausgewählt hast. Wenn du deinen Persönlichen Stundenplan auslesen willst (also Student) dann deinen vor und Nachnamen wie in der [ReadMe](https://discord.gg/34EHnHQaPm).
Wenn du ein Stundenplan der Klasse willst dein Klasse

> Aber leider geht der Discord link nicht.

der in der ReadMe sollte gehen
https://discord.gg/34EHnHQaPm

**Comment by mcpdev80** [comment]
Ok, danke der Link den du mir geschickt hast, geht ;-)

Das ist der Link, der in der Readme steht.
https://discord.com/channels/1090218586565509170/1208159703520120902

Vorschlag: Bei der Beschreibung wäre es vielleicht gut, wenn dort Beispiele angegeben wären und dass "/" = "or" heißt ;-)

Full Name or Class or Subject or Room
example for Full Name: Max John, Mustermann

**Comment by JonasJoKuJonas** [comment]
> Vorschlag: Bei der Beschreibung wäre es vielleicht gut, wenn dort Beispiele angegeben wären und dass "/" = "or" heißt ;-)

bin grad dabei

funktioniert es jetzt?

**Comment by mcpdev80** [comment]
Hi, ja konnte eine Verbindung herstellen ;-)
