### ISSUE TITLE
get homeworks

### ISSUE THREAD

**Issue by User7872953326** [JonasJoKuJonas/homeassistant-WebUntis#125]
Is there any way to show homework in Home Assistant? Maybe in the calendar? It would be great if there was a way to get the homework. For example, you could create an automation that fetches next week's homework and puts it in a local to-do list.

**Comment by JonasJoKuJonas** [comment]
This is currently not possible via the official webuntis API.

https://github.com/python-webuntis/python-webuntis/issues/58

**Comment by SeriousM** [comment]
How about implement inofficial apis?
This looks like a solution to me: https://github.com/python-webuntis/python-webuntis/issues/49#issuecomment-1916249549

**Comment by JonasJoKuJonas** [comment]
addet in v1.3.0

**Comment by gclever** [comment]
I second this! Please make the homework info available via "todo.add_item"!

**Comment by humplemann** [comment]
+1
