### ISSUE TITLE
Stunden mit keinen Fächern anzeigen

### ISSUE THREAD

**Issue by techmaved** [JonasJoKuJonas/homeassistant-WebUntis#129]
Hat eine Stunde keine Fächer wird diese von der Integration ignoriert. Das führt dazu, dass Automationen, die den Schulanfang/-ende mit einbeziehen eine falsche Zeit verwenden. Auch zeigt der Kalender diese Stunden nicht an.

**Änderungsvorschlag:**
Stunden ohne Fächer im Kalender und in den heutigen Schulanfang/-ende Sensoren mit einbeziehen.

**Comment by f-zappa** [comment]
Bei uns steht z.B. morgen ein Wandertag an, der im Untis auch angezeigt wird, aber die Integration kennt ihn nicht. Würde so etwas davon auch mit profitieren?

**Comment by kuechr4** [comment]
Ja, wenn die Stunde kein Fach enthält wurde sie durch diese Änderung auch angezeigt werden können.

**Comment by JonasJoKuJonas** [comment]
add in v1.2.1
