### ISSUE TITLE
Schulklassen wechseln

### ISSUE THREAD

**Issue by evilmumi** [JonasJoKuJonas/homeassistant-WebUntis#132]
### The problem

Hi,

nachdem nun das neue Schuljahr angefangen hat, wie wechsel ich z.b. von der 7.2 in die 8.1 ?

### Version of Home Assistant?

2024.7.4

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

1.13

**Comment by evilmumi** [comment]
Hi, die Klasse war / ist gar nicht in der Konfig hinterlegt.
Jetzt geht es.

**Comment by JonasJoKuJonas** [comment]
Das kommt darauf an, wie du die Integration eingerichtet hast. Wenn du den Stundenplan für einen Schüler oder Lehrer gewählt hast funktioniert es ohne Probleme.
Es wird aber wahrscheinlich mit dem nächsten Update eine Funktion geben, mit der bei der Einrichtung direkt der persönlichen Stundenplan gewählt wird.
