### ISSUE TITLE
Fächer umbenennen

### ISSUE THREAD

**Issue by evilmumi** [JonasJoKuJonas/homeassistant-WebUntis#133]
Ist es möglich, die Fächer umzubenennen?
Mit "PoWi" und "AUF DE" ist es nicht immer leicht sofort zu erkennen was es ist.

Zur Anzeige nutze ich type: custom:atomic-calendar-revive
Es nutzt den   - entity: calendar.schuelername_webuntis_calender

**Comment by JonasJoKuJonas** [comment]
Aktuell ist das über die Integration nicht möglich, ist aber eine Idee für ein neues Feature ♥️

**Comment by sevorl** [comment]
Dieses Feature fände ich auch nützlich.

Aktuell "hacke" ich mir das immer manuell in die Datei /homeassistant/custom_components/webuntis/__init__.py

Das ist aber nach jedem Update weg. (Und wahrscheinlich geht das insgesamt eleganter...).

So sieht das bei mir aus: 


            if self.check_lesson(
                lesson, ignor_cancelled=self.calendar_show_cancelled_lessons
            ):
                try:
                    event = {}

                    prefix = ""
                    if self.calendar_show_room_change and lesson.original_rooms:
                        prefix = "🔀  "
                    if self.calendar_long_name:
                        event["summary"] = prefix + lesson.subjects[0].long_name.replace(", Beginn in Jahrgangsklasse 7", "").replace(", Beginn in Jahrgangsklasse 5", "").replace("Evangelische Religionslehre", "Religion").replace("Kunsterziehung", "Kunst").replace("Lateinisch", "Latein")

                    else:
                        event["summary"] = prefix + lesson.subjects[0].name

                    if lesson.code == "cancelled":
                        event["summary"] = "❌ " + event["summary"]

**Comment by evilmumi** [comment]
Wie muss ich das verstehen.
Ersetzt er Religion durch Evangelische Religionslehre oder andersrum?

**Comment by sevorl** [comment]
Andersherum. Die Namen, welche von der Schule verwendet werden, sind mit zu
lang. Im Kalender will ich kürzere Namen anzeigen


|


evilmumi ***@***.***> schrieb am Do. 22. Aug. 2024 um 14:44:

**Comment by JonasJoKuJonas** [comment]
add in v1.2.3

**Comment by sevorl** [comment]
Super, vielen Dank.
Hinweis: Nach dem Update wurde die Integration bei mir zunächst nicht geladen.
nachdem ich einen Text in der Ersetzen-Liste eingetragen habe, konnte die Erweiterung dann geladen werden. Vielleicht ein Problem, wenn die Liste leer ist?

Logger: homeassistant.config_entries
Quelle: config_entries.py:604
Erstmals aufgetreten: 20:33:09 (2 Vorkommnisse)
Zuletzt protokolliert: 20:33:09


Error setting up entry *********** for webuntis
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/__init__.py", line 59, in async_setup_entry
    server = WebUntis(hass, unique_id, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/__init__.py", line 169, in __init__
    self.calendar_replace_name = config.options["calendar_replace_name"]
                                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'calendar_replace_name'

**Comment by JonasJoKuJonas** [comment]
> Hinweis: Nach dem Update wurde die Integration bei mir zunächst nicht geladen. nachdem ich einen Text in der Ersetzen-Liste eingetragen habe, konnte die Erweiterung dann geladen werden. 

Das hatte ich auch erst hab es aber schon gefixt 👍🏼
Danke für die Rückmeldung

**Comment by sevorl** [comment]
Und noch eine Idee:

Wenn die Zeile 640
                    if lesson.code == "cancelled":
                        event["summary"] = "Cancelled: " + event["summary"]

weiter oben stünde, könnte man Cancelled einfach durch einen anderen Text ersetzen aus der Ersetzungsliste.
Für Roomchange sowie für Stunden ohne Titel ("None") wäre das auch schön...
