### ISSUE TITLE
Veranstaltungen mit anzeigen

### ISSUE THREAD

**Issue by evilmumi** [JonasJoKuJonas/homeassistant-WebUntis#135]
Wir haben den Fall, dass Stunden ausfallen und mit einer Veranstaltung ersetzt werden.
z.b. Klassenfahrt oder Schulfest
Ist das möglich in HA sichtbar zu machen?

![grafik](https://github.com/user-attachments/assets/5c6df6ba-02f0-4ec1-9317-1bd5a1695438)

**Comment by sevorl** [comment]
Isn't this the same as https://github.com/JonasJoKuJonas/homeassistant-WebUntis/issues/54 ?
(I would love to see this feature...)

**Comment by evilmumi** [comment]
korrekt, wieso hat er mir das nicht angezeigt, hum

**Comment by JonasJoKuJonas** [comment]
I don't know if the Python packages have the ability to do this

**Comment by JonasJoKuJonas** [comment]
duplicate of #54
