### ISSUE TITLE
Was soll ich bei Name und und klasse eintrage?

### ISSUE THREAD

**Issue by NotRin7** [JonasJoKuJonas/homeassistant-WebUntis#14]

**Comment by JonasJoKuJonas** [comment]
Bei der Stundenplan Quelle gibst du die Daten von dem Studenplan deiner Klasse oder deinem Persönlichen sehen willst.
Bei Name/ Klasse/ Fach/ Raum gibst du dann dementsprechend dein Name oder deine Klasse an.

**Comment by NotRin7** [comment]
Danke für deine Antwort leuft jetzt alles danke!

Jonas ***@***.***> schrieb am Di., 8. Nov. 2022, 17:41:

**Comment by JonasJoKuJonas** [comment]
README.md aktualisiert!
