### ISSUE TITLE
Homework todo/done/time 

### ISSUE THREAD

**Issue by SeppLange** [JonasJoKuJonas/homeassistant-WebUntis#140]
Hi!

Maybe it's already done, but I don't see it.
But: Is it possible to get the homework data out of web untis? The calendar etc. works perfectly, but I don't get any information about the homework, which is described online, when you have logged into web untis.

I've attached a web untis online screen (in German) with the topic "Hausaufgaben", which means "home work".

--->
![homework](https://github.com/user-attachments/assets/78206e69-591e-43b2-bd42-d58c2dd26f49)
<---

Thanks a lot!

BR,
Sebastian

**Comment by evilmumi** [comment]
siehe auch https://github.com/JonasJoKuJonas/homeassistant-WebUntis/issues/125

**Comment by JonasJoKuJonas** [comment]
Duplicate #125
