### ISSUE TITLE
sensor.xxx_todays_school_end shows hours until event instead of time

### ISSUE THREAD

**Issue by bill340** [JonasJoKuJonas/homeassistant-WebUntis#143]
### The problem

If I show the sensor for today's school end in a card, it shows me how long until school end. (e.g. 7 hours)
But I would like to see at what time the school ends today. (e.g. 2:30pm) without the date.

### Version of Home Assistant?

2024.9.1

### What type of installation are you running?

Home Assistant Container

### Version of WebUntis

v1.2.0

**Comment by JonasJoKuJonas** [comment]
This is not an issue on my integration. You have to use a other card or a template to show the time. The normal entities card will show the Time untill. Use the entity card or get the time via a template.
![IMG_0179](https://github.com/user-attachments/assets/50a2b6a5-c292-471a-a92c-f3e49b3a04bf)

```
type: entity
    entity: sensor.jonas_kuehn_today_school_end
```

```
type: entities
entities:
  - entity: sensor.jonas_kuehn_today_school_end
```

**Comment by bill340** [comment]
Thank you very much!!
Is it possible to show the time without the date? 
As it is always today?

**Comment by bill340** [comment]
Thats it!!!
THANK YOU SO MUCH!!!
Also for your great work!!
