### ISSUE TITLE
Stundenplan von Parallelklasse wird mit angezeigt

### ISSUE THREAD

**Issue by bill340** [JonasJoKuJonas/homeassistant-WebUntis#146]
### The problem

Neben dem eigenen Stundenplan wird auch der Stundenplan der Parallelklasse dargestellt.
s. Screenshot
<img width="504" alt="Bildschirmfoto 2024-09-12 um 22 42 56" src="https://github.com/user-attachments/assets/cf6cdd08-06c2-4616-87e7-aed539e32843">

### Version of Home Assistant?

2024.9.1

### What type of installation are you running?

Home Assistant Container

### Version of WebUntis

1.2.2

**Comment by JonasJoKuJonas** [comment]
Über welche Methode hast du die Integration eingerichtet?

**Comment by bill340** [comment]
Problem ist behoben. Nach Neuinstallation funktioniert jetzt alles.
