### ISSUE TITLE
UID des Events ist None

### ISSUE THREAD

**Issue by GitGramm** [JonasJoKuJonas/homeassistant-WebUntis#147]
### The problem

Vielen Dank für das erstellen dieses Add-ons!

Ich habe versucht mit https://github.com/JosephAbbey/ha_calendar_export ein .ics zu erzeugen und den Kalender auf dem iPhone anzuzeigen.
Leider zeigt es dann nur einen (den letzten) Termin an.
Im .ics sind alle Events enthalten aber die UID auf bei allen auf "none" gesetzt.
Vielleicht könnte es gefixed werden, wenn in calender.py noch `import uuid` und an der richtigen Stelle `event.uid = uuid.uuid4()` hinzugefügt wird?

### Version of Home Assistant?

2024.8.2

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v1.2.0

**Comment by JonasJoKuJonas** [comment]
fixed in v1.2.3
