### ISSUE TITLE
Failed to setup after upgrade today

### ISSUE THREAD

**Issue by Cyrelion** [JonasJoKuJonas/homeassistant-WebUntis#148]
### The problem

Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 20:58:40 (2 occurrences)
Last logged: 21:02:35

Error setting up entry XXXXXX for webuntis
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/__init__.py", line 59, in async_setup_entry
    server = WebUntis(hass, unique_id, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/__init__.py", line 169, in __init__
    self.calendar_replace_name = config.options["calendar_replace_name"]
                                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'calendar_replace_name'

### Version of Home Assistant?

2024.9.2

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

1.2.3

### Last working WebUntis version

1.2.2

### Traceback/Error logs

Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 20:58:40 (2 occurrences)
Last logged: 21:02:35

Error setting up entry XXXXXX for webuntis
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/__init__.py", line 59, in async_setup_entry
    server = WebUntis(hass, unique_id, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/__init__.py", line 169, in __init__
    self.calendar_replace_name = config.options["calendar_replace_name"]
                                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'calendar_replace_name'

### Additional information

_No response_

**Comment by Cyrelion** [comment]
After downgrade to 1.2.2 everything is working again.

**Comment by Cyrelion** [comment]
Achso, genau der Fehler den ihr hier diskutiert habt: https://github.com/JonasJoKuJonas/homeassistant-WebUntis/issues/133#issuecomment-2356641594

**Comment by JonasJoKuJonas** [comment]
Der commit mit dem fix wurde anscheinend doch nicht ins update übernommen

**Comment by JonasJoKuJonas** [comment]
jetzt aber
v1.2.4

**Comment by Cyrelion** [comment]
Leider nicht ;-( 1.2.4 geht immer noch nicht

**Comment by JonasJoKuJonas** [comment]
sorry war grad nur am handy und hab die falsche Zeile erwischt
habs jetzt am Laptop gefixt

**Comment by Cyrelion** [comment]
Vielen Dank. Jetzt klappt alles 🥰
