### ISSUE TITLE
Feature request: new messages, calendar

### ISSUE THREAD

**Issue by umrath** [JonasJoKuJonas/homeassistant-WebUntis#15]
Nice idea and great potential.

Would very much like to see a fucntionality that displays new messages, a new messages counter or the like.
Also, importing the calendar could be useful.

Essentially, exposing all information of Untis would be useful, as it would allow to work around the rather ugly app/web interface.

**Comment by JonasJoKuJonas** [comment]
The new messages aren't available in the Units API, so I can't implement this feature.

**Comment by umrath** [comment]
Too bad.
So, the API is essentially as bad as the whole product. No real surprise here. :(
