### ISSUE TITLE
Stunden Name ersetzen funktioniniert nicht mehr für Cancelled, Room change, Irregular

### ISSUE THREAD

**Issue by sevorl** [JonasJoKuJonas/homeassistant-WebUntis#159]
### The problem

Erstmal vielen Dank für das Update auf v1.3.0! Toll, wie du Untis immer weiterentwickelst.

Ich verwende in der Ersetzungsliste unter anderem: 
Cancelled: ❌
Room change: 🔀
Irregular: Sonderstunde

Diese Begriffe werden in dem neuen Update nicht mehr ersetzt, es erscheinen die englischen Texte.
Stundennamen werden jedoch weiterhin ersetzt.

### Version of Home Assistant?

2024.10.1

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v1.3.0

**Comment by sevorl** [comment]
Ich denke ich hab es selbst gefunden. RTFM. ;-)

Diese Texte werden jetzt an anderer Stelle konfiguriert als vorher...

**Comment by JanGrosse** [comment]
@sevorl  Eventuell kannst du oder jemand anderes mir dann helfen bzw. auf die Stelle im Manual verweisen zum readen wo das erklärt wird 😄
Ich habe die Einstellung unter "Konfigurieren" => "Kalender" genommen und es wie folgt eingestellt - einfach einmal das genannte Beispiel ausprobiert um "Cancelled" zu ersetzen.
![grafik](https://github.com/user-attachments/assets/e8860bcb-60be-42f0-ae8b-dabad319c9f6)


Aber im Kalender wird es nicht ersetzt (siehe hier Englisch von 12:00 - 12:45). 
Habe auch die WebUntis Integration einmal neu geladen, auch ohne Erfolg.
![grafik](https://github.com/user-attachments/assets/65625242-d030-466d-be0f-18a073494f93)


Vielen Dank.

**Comment by JonasJoKuJonas** [comment]
Da ist mir bei dem großen rework wohl ein Fehler unterlaufen und calendar_replace_name wird aktuell nicht beachtet.
Habs aber gefixt und funktioniert mit dem nächsten update ;)
