### ISSUE TITLE
Error entering *Schule

### ISSUE THREAD

**Issue by MartinG1985** [JonasJoKuJonas/homeassistant-WebUntis#164]
Hello Jonas,

I have an Issue filling out the login data. 

I tried many options für *Schule but didn't yet find a solution to find the right one. What do I do wrong?

Please help me.

Best regards

Martin

![Webuntis Integration Error](https://github.com/user-attachments/assets/641f7f41-371a-463c-bda9-8d2908a8baf9)

**Comment by JonasJoKuJonas** [comment]
If you look at the URL you have the parameter school. That is what should work. In you case it starts with FE...

**Comment by MartinG1985** [comment]
Hello,

I tried it. Unfortunately it is still not working. 

![image](https://github.com/user-attachments/assets/54f3cc30-046e-42a8-9ad6-f1a3a76e8707)

**Comment by evilmumi** [comment]
Schau dir nochmal den Punkt in der Doku https://github.com/JonasJoKuJonas/homeassistant-WebUntis?tab=readme-ov-file#configuration-via-ui an.
Bei Server nur den Server rein.

**Comment by MartinG1985** [comment]
Wow, das war schnell. Hat bestens funktioniert. Bin echt begeistert. Danke!
