### ISSUE TITLE
Webuntis Kalender mit Googlekalender

### ISSUE THREAD

**Issue by derGreyson** [JonasJoKuJonas/homeassistant-WebUntis#167]
Hi,

ich habe eine Frage. Da aktuell Homeassistant nicht aktiv als Kalender genutzt wird, was sicherlich an meinen Fähigkeiten liegt.
Ich möchte gerne den Kalender, der in Homeassistant von Webuntis bereitgestellt wird in Google anzeigen lassen.

Ist das möglich?

**Comment by RealJustMe** [comment]
Hey, soweit ich weiß, geht das nicht in Home Assistant selber. Du könntest das HACS Add-on [Calendar Export](https://github.com/josephabbey/ha_calendar_export) dafür nutzen.

**Comment by JonasJoKuJonas** [comment]
Ich nutze dazu [ha_calendar_export](https://github.com/JosephAbbey/ha_calendar_export).
Dazu musst du aber dein HA auch extern erreichen können
