### ISSUE TITLE
Wrong information in homework calender - 2 kids same school

### ISSUE THREAD

**Issue by willowHASS** [JonasJoKuJonas/homeassistant-WebUntis#169]
### The problem

I have two children from the same school.
In the homework calendar, daughter 1 shows daughter 2's homework.

![IMG_9813](https://github.com/user-attachments/assets/bd8855f1-b20a-4742-a8a4-6650f9cc7c62)
![IMG_9814](https://github.com/user-attachments/assets/0d1abe35-a8cb-4179-8bd0-ef9a279564a3)

### Version of Home Assistant?

Core 2024.10.4 Supervisor 2024.10.3 Operating System 13.2 Frontend 20241002.4

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v1.3.2

**Comment by JonasJoKuJonas** [comment]
Do you have 2 separat logins (usernames and passwords)?
What happens if you temporary deactivate on of the configs?

**Comment by willowHASS** [comment]
No I am using the parents account. It might be possible that it is the same issue as #168. At the moment the exam calender is empty at both kids.

This week the kids have holiday, I will monitor it next week when school starts.

**Comment by JonasJoKuJonas** [comment]
Although holiday you should see homework in the Calendar tab from the past 30 days

**Comment by willowHASS** [comment]
Yes you are right. I see for all the days for both kids the same homework content.
For Salome it is the right content for Eva it is the wrong content.

**Comment by willowHASS** [comment]
Ok I think the problem is a little bit different as I wrote at the beginning. If kid 1 has homework I se it also at kid 2 and reversed.

**Comment by JonasJoKuJonas** [comment]
so homework from both kids is displayed in both calendars 

this is probably what the webapp shows.

do you see any Information on this site that could keep the homework apart (like Klasse or Schüler)?
![image](https://github.com/user-attachments/assets/91d7f174-2f7c-4427-a004-d43ca4cb67f0)

**Comment by willowHASS** [comment]
Yes, in the Hausaufgaben table I find both Schüler Eva and Salome.

If it would be possible to differentiate the calender by the Schüler name that would be perfect.

![image](https://github.com/user-attachments/assets/ac06d613-b1ef-406d-9a56-1f6297e41f43)

**Comment by JonasJoKuJonas** [comment]
could you test version v1.3.3.beta
i added a student filter for the homework if you set up the integration via "Schüler"

**Comment by willowHASS** [comment]
I get a failure message in the log:


Logger: homeassistant.setup
Quelle: setup.py:269
Erstmals aufgetreten: 17:24:39 (1 Vorkommnisse)
Zuletzt protokolliert: 17:24:39

Setup failed for 'webuntis': Integration not found.

**Comment by willowHASS** [comment]
Here are some more details:

2024-10-31 17:24:37.649 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration webuntis which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-31 17:24:37.649 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'webuntis' does not have a valid version key (v1.3.3.beta) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
2024-10-31 17:24:38.240 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Integration 'webuntis' not found.
2024-10-31 17:24:39.865 ERROR (MainThread) [homeassistant.setup] Setup failed for 'webuntis': Integration not found.
homeassistant.loader.IntegrationNotFound: Integration 'webuntis' not found.
homeassistant.loader.IntegrationNotFound: Integration 'webuntis' not found.
homeassistant.loader.IntegrationNotFound: Integration 'webuntis' not found.

**Comment by JonasJoKuJonas** [comment]
try updating again

**Comment by willowHASS** [comment]
Now Webuntis is working 👍



At first glance it looks correct.

I deleted both old integrations and add the with the Option "Schüler".

Now I see only the Homework of each kid. Currently I am in holiday and I have only my iPhone available.
Next week I am back home then I will do a more detailed check.

Thank you very much 💪🏼 great work!

**Comment by willowHASS** [comment]
Hi @JonasJoKuJonas, today I tested all the homework data and all is available and correct.
You could close that issue.

Thanks

**Comment by willowHASS** [comment]
Closing the issue
