### ISSUE TITLE
Time zone issue

### ISSUE THREAD

**Issue by cicero200272** [JonasJoKuJonas/homeassistant-WebUntis#17]
The component as such works fine for me, but all times use the wrong time zone. 

The first lesson starts at 8 AM local time. Although my HA instance is set to "(GMT+01:00) Berlin" time zone, the sensors show me the time in UTC time zone: `2022-11-10T08:00:00+00:00`. 

As a consequence, everything is shifted by one hour, the binary_sensor switches to "on" at 09:00 instead of 08:00 etc.

Could you please check that? Thanks in advance! :-)

**Comment by JonasJoKuJonas** [comment]
Can you give me more information about you home assistant instance?

- Are you running it in a Docker?
- Which timezone are you currently in?

**Comment by cicero200272** [comment]
Hi Jonas, thanks for looking into this!

Are you running it in a Docker? -> yes
Which timezone are you currently in? -> (GMT+01:00) Berlin

The times are correct themselves, but are delivered in UTC time zone (e. g. next lesson starts at 11:30 local time):
![image](https://user-images.githubusercontent.com/15817602/201326924-f37f0582-7e80-4adf-9955-4ea5724b3112.png)

All other dates / timestamps in HA are correct.

**Comment by JonasJoKuJonas** [comment]
I did some research and found out that the time zone is always in UTC format. This is not a bug!
[UTC & Time zone awareness](https://www.home-assistant.io/blog/2015/05/09/utc-time-zone-awareness/)

**Comment by cicero200272** [comment]
Jonas,

The issue is not that the date/time is formatted in UTC, the issue is that the time is wrong.

The first lesson starts at 08:00 local time. The component should therefore provide 2022-11-14T0**7**:00:00+00:00. Since I live in a time zone one hour past UTC, 08:00 local time means 07:00 in UTC.

Instead, the time the component provides is 2022-11-14T0**8**:00:00+00:00 which is the equivalent of 09:00 local time. So Home Assistant shows me 09:00 since it converts all times into my local time zone.

Please reconsider looking into this, there must be something wrong with either Untis' response format or the time formatting of the component.

**Comment by JonasJoKuJonas** [comment]
What time zone is your docker set to?

**Comment by JonasJoKuJonas** [comment]
What time zone is your docker set to?

**Comment by cicero200272** [comment]
Since I run the default HA docker image and there is no dedicated time zone defined there, it is most likely UTC.

So `astimezone()` seems to be the culprit since it defaults to the serve time zone (which is UTC in my case). Let me try to explicitly set a time zone in my docker container - hopefully this won't break other datetime features within HA...

**Comment by cicero200272** [comment]
OK, now it seems to work:

![screenshot](https://user-images.githubusercontent.com/15817602/201532897-96a41f39-08b1-4198-b60d-95bb76b0ccdf.png)

Perhaps you could add a hint in the readme.me for docker users that it's necessary to add the local timezone?
This ticket can be closed then I think :-)

Thanks a lot & keep up the good work!

**Comment by JonasJoKuJonas** [comment]
Add hint for docker users with local timezone in README.md
