### ISSUE TITLE
"teachers" automatically excluded in backend / "teachers" automatisch im Backend ausgeschlossen

### ISSUE THREAD

**Issue by ErniePi** [JonasJoKuJonas/homeassistant-WebUntis#170]
### The problem

I only have access to a class calendar on Untis - no personal student calendar.
Import of data works well and I can see lessons in the Calendar View.
But there is no "teacher" data - even in the JSON (e.g. NAME_next_lesson_to_wake_up).
From what I see this is due to automatic exclusion of "teachers" in the "Backend Settings" of the configuration.
How can this solved?
-------
Ich habe nur Zugriff auf einen Klassenkalender in Untis - keinen persönlichen Schülerkalender.
Der Import der DAten funktioniert gut und ich kann die Unterrichtsstunden im Kalender sehen.
Aber es gibt keine "Lehrer" Informationen - auch nicht im JSON (z.B. NAME_next_lesson_to_wake_up).
Meiner Meinung nach beruht das auf einem automatischen Ausschluss von "Lehrer"/"teachers" in den "Backend Settings" der Konfiguration.
Wie kann man dies lösen?
![image](https://github.com/user-attachments/assets/a62c6733-7bb7-416e-aef8-c1fc12df7018)

### Version of Home Assistant?

2024.10.4

### What type of installation are you running?

Home Assistant Core

### Version of WebUntis

v1.3.2

**Comment by ErniePi** [comment]
Please close this issue as this has been a topic - and been resolved (no rights to access this information) - before.

Sorry for raising this issue.

P.S.: Although I see the information in the Untis App/website. Weird that I don't have the rights to that information.

**Comment by JonasJoKuJonas** [comment]
The integration automatically excluded teachers if you have no permission on to API to get the teachers name.
This will prevent your logs from getting spammed.

**Comment by ErniePi** [comment]
Thank you. Maybe append the read.me to mention this?
I - unfortunately - only looked in "open" issues before raising a new one. Found the reason in the closed issues only afterwards...
