### ISSUE TITLE
Stunden-Name ersetzen matcht Teilstrings

### ISSUE THREAD

**Issue by macmeck** [JonasJoKuJonas/homeassistant-WebUntis#173]
### The problem

Das Ersetzen der Stundennamen ersetzt bereits den erstmöglichen Teil anstatt des gesamten Namens.

Konfiguration:
```
M: Mathe
Mu: Musik
```

ersetzt `Mu` zu `Matheu` anstatt zu Musik.

### Version of Home Assistant?

24.11.1

### What type of installation are you running?

Home Assistant Supervised

### Version of WebUntis

v1.3.3

**Comment by JonasJoKuJonas** [comment]
fixed in next version
[lesson_replace_name only full match](https://github.com/JonasJoKuJonas/homeassistant-WebUntis/commit/844e4974bcd435200b8b7043dc24312094e6eef6)
