### ISSUE TITLE
Wann ist morgen Schulschluss

### ISSUE THREAD

**Issue by evilmumi** [JonasJoKuJonas/homeassistant-WebUntis#176]
Ich habe gerade mit Alexa eine Routine die mir die Frage beantwortet, wann die Kinder morgen Schulbeginn haben.
Wäre es möglich auch Schulschluss zu erkennen oder sogar als Sensor zu bekommen.
Ala sensor.schueler_tommorow_school_end oder sensor.schuler_last_lesson_to_say_goodbye

**Comment by humplemann** [comment]
+1

**Comment by JonasJoKuJonas** [comment]
Du kannst einen template sensor erstellen, um das ende des morgigen Tages herauszufinden.
Die Daten liegen alle im next lesson to wake up sensor `day` attribut

```
{% set x = state_attr("sensor.NAME_next_lesson_to_wake_up", "day") | from_json %}

{{ x[-1]["end"] }}
```

**Comment by evilmumi** [comment]
> Du kannst einen template sensor erstellen, um das ende des morgigen Tages herauszufinden. Die Daten liegen alle im next lesson to wake up sensor `day` attribut
> 
> ```
> {% set x = state_attr("sensor.NAME_next_lesson_to_wake_up", "day") | from_json %}
> 
> {{ x[-1]["end"] }}
> ```
Danke. Das habe ich genau so gesucht !
