### ISSUE TITLE
Unerwarteter Fehler bei Eingabe der Zugangsdaten

### ISSUE THREAD

**Issue by srausse** [JonasJoKuJonas/homeassistant-WebUntis#19]
Bei Eingabe der Daten laut der readme kommt nur die Meldung "Unerwarteter Fehler".

Aus dem Link https://borys.webuntis.com/WebUntis/?school=Gym+JuM+Ochtrup#/basic/login habe ich folgendes übernommen:

Server = borys.webuntis.com
Schule = Gym+JuM+Ochtrup

Die Zugangsdaten sind Klassenweise vergeben, daher waren neben den zugeteilten Benutzer und Passwort meine weiteren Einstellungen:

Stundenplan Quelle = klasse
Ganzer Name = 09c (identisch zum Benutzernamen)

Was mache ich falsch bzw. kann was könnte ich ausprobieren?

**Comment by srausse** [comment]
Noch eine Ergänzung:

Mit den Zugangsdaten zu einer weiteren Klasse bekomme ich den selben Fehler...

**Comment by JonasJoKuJonas** [comment]
Was steht in den Logs?

**Comment by srausse** [comment]
Hallo,

das habe ich mir gerade aus dem Protokoll vom Docker gezogen:

2022-11-12 18:08:56.563 ERROR (MainThread) [custom_components.webuntis.config_flow] Unexpected exception
stdout
18:08:56
Traceback (most recent call last):
stdout
18:08:56
  File "/config/custom_components/webuntis/config_flow.py", line 154, in async_step_user
stdout
18:08:56
    info = await validate_input(self.hass, user_input)
stdout
18:08:56
  File "/config/custom_components/webuntis/config_flow.py", line 100, in validate_input
stdout
18:08:56
    source = klassen.filter(name=timetable_source_id)[0]
stdout
18:08:56
  File "/usr/local/lib/python3.10/site-packages/webuntis/objects.py", line 180, in __getitem__
stdout
18:08:56
    data = self._data[i]  # fails if there is no such item
stdout
18:08:56
IndexError: list index out of range


Wenn das falsch ist, einfach einen Hinweis geben, womit ich es machen soll. Sowas ist für mich das erste Mal ;)


Viele Grüße
Stefan Rauße

**Comment by JonasJoKuJonas** [comment]
Du hast eine Klasse angegeben die es nicht gibt!

**Comment by JonasJoKuJonas** [comment]
Wenn du das nächste mal logs oder Befehle teilst, formatiere sie.
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code
```
2022-11-12 18:08:56.563 ERROR (MainThread) [custom_components.webuntis.config_flow] Unexpected exception
stdout
18:08:56
Traceback (most recent call last):
stdout
18:08:56
  File "/config/custom_components/webuntis/config_flow.py", line 154, in async_step_user
stdout
18:08:56
    info = await validate_input(self.hass, user_input)
stdout
18:08:56
  File "/config/custom_components/webuntis/config_flow.py", line 100, in validate_input
stdout
18:08:56
    source = klassen.filter(name=timetable_source_id)[0]
stdout
18:08:56
  File "/usr/local/lib/python3.10/site-packages/webuntis/objects.py", line 180, in __getitem__
stdout
18:08:56
    data = self._data[i]  # fails if there is no such item
stdout
18:08:56
IndexError: list index out of range
```
Das kann man dann besser lesen

**Comment by JonasJoKuJonas** [comment]
Neue Fehlermeldung wenn keine Klasse gefunden wurde hinzugefügt (v0.1.4)

**Comment by srausse** [comment]
Super Danke für die Hilfe und den Hinweis zur Formatierung.

Update gerade gemacht und die Fehlermeldung kommt wie beschrieben.

Dann muss ich jetzt scheinbar für die Schule nur noch die korrekten Parameter in Erfahrung bringen ;)
