### ISSUE TITLE
Wohin mit der Konfiguration?

### ISSUE THREAD

**Issue by elearningdienst** [JonasJoKuJonas/homeassistant-WebUntis#22]
Wohin kommt denn die Konfiguration also URL, Passwort und der Nutzername sowie die Klasse?

**Comment by JonasJoKuJonas** [comment]
Du kannst diese Integration über das UI konfigurieren.

**Comment by elearningdienst** [comment]
Leider nicht. Ich finde nirgends eine Möglichkeit das einzutragen. Bug?

**Comment by JonasJoKuJonas** [comment]
Hast du den Browser Cash gelöscht und die Seite neu geladen?

**Comment by banthungprong** [comment]
Ebenso hier. Keine UI-Integration (Cache gelöscht etc). Auch über HACS installiert.
Ordner "webuntis" unterhalb von "custom_components" ist vorhanden. Keine Infos in den Logs.

**Comment by JonasJoKuJonas** [comment]
Funktionieren bei die andere custom component über die UI?

**Comment by JonasJoKuJonas** [comment]
Was befindet sich in dem WebUntis Ordner?

**Comment by banthungprong** [comment]
![image](https://user-images.githubusercontent.com/59219161/204477822-611c3522-cde9-4088-9f8f-976c86b0a83b.png)

**Comment by JonasJoKuJonas** [comment]
Wird die Integration in der Logdatei geladen?

**Comment by JonasJoKuJonas** [comment]
Hast du das Problem nur bei WebUntis oder auch bei anderen custom component von Hacs

**Comment by banthungprong** [comment]
Bei anderen ok.

**Comment by MarcFu** [comment]
> Funktionieren bei die andere custom component über die UI?

Ja, ich habe es eingerichtet über die UI (mit Chrome)

**Comment by banthungprong** [comment]
Even with the latest updates not working. Removed it from my HA installation.

**Comment by JonasJoKuJonas** [comment]
Set the Log Level to INFO and see again in the logs.
You should get this info:
```INFO (SyncWorker_5) [homeassistant.loader] Loaded webuntis from homeassistant.components.webuntis```

I need some other Information about your Installation.
HA-Version?
Docker?
Hardware?

**Comment by greveler** [comment]
It worked for me! Nice integration.

Maybe for some users who are rather new to HA it would help to add to the documenntation that after installation and restart you have to manually add the integration via UI and then credentials are requested via UI.

**Comment by Woem6** [comment]
Hi,
I have a similar problem, I can't find the UI. Where should it be?
I tried clearing cache and logging only throws out 
"2023-02-07 16:18:02.211 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration webuntis which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant"
HACS works (I'm running kiosk mode)
I run HA on Docker (20.10.21, build baedalf), Raspi 3B, HA Ver. 2023.2.2
Any ideals or suggestions?

**Comment by Woem6** [comment]
Ups, same here: sorry for bothering you! 
I did not realize that the integration has to be installed via HACS first and then via Configuration->Integrations. I had expected that to be via HACS and was frustrated that I did not find any Install or Config button. 
Maybe you could add that to the instruction to make it ideot-proof for noobs like me.

**Comment by niklasbaranski** [comment]
is the issue still happening?

**Comment by niklasbaranski** [comment]
and for the others?
@banthungprong 
@elearningdienst

**Comment by banthungprong** [comment]
Update:
Changed password, removing all special characters. Login ist working. So there is a mistake in the sources with the password string (maybe \ not interpreted correctly).
