### ISSUE TITLE
Bug: max days in atomic-calendar-revive

### ISSUE THREAD

**Issue by sevorl** [JonasJoKuJonas/homeassistant-WebUntis#24]
Der neue Kalender verhält sich anders als andere Kalender (Google Calender)  in HA.

In dem Custom-Calender "https://github.com/totaldebug/atomic-calendar-revive/" funktioniert die Anzeige der "Max days to show" nicht. 

Ich kann leider nicht prüfen, ob dies ein Problem des untis-Kalender-Sensors ist, oder von atomic-calender.

Beispiel - so funktioniert es mit einem Google Calender: 

type: custom:atomic-calendar-revive
name: Calendar Card
enableModeChange: true
entities:
  - entity: calendar.familie
    name: Familie
firstDayOfWeek: 1
maxDaysToShow: 1
refreshInterval: 60

Bei dem Untis-Kalender hat der Parameter "maxDaysToShow" keine Wirkung:
type: custom:atomic-calendar-revive
name: Calendar Card
enableModeChange: true
entities:
  - entity: calendar.xxxxx_webuntis_calender
    name: WebUntis Calender
firstDayOfWeek: 1
maxDaysToShow: 1
refreshInterval: 60

**Comment by sevorl** [comment]
Zusatz: Der Parameter "startDaysAhead:" funktioniert auch nicht.

**Comment by sevorl** [comment]
Vielleicht interessant: Home Assistant 2022.12 wird lokale Kalender unterstützen: https://rc.home-assistant.io/blog/2022/11/30/release-202212/#local-calendar

**Comment by JonasJoKuJonas** [comment]
Ich habe gerade durch Zufall den Fehler gefunden!
Er wird in der nächsten Version behoben sein!
v0.5.3 oder höher

**Comment by sevorl** [comment]
Super! Vielen Dank
