### ISSUE TITLE
Feature request: list student-absences (Abwesenheiten)

### ISSUE THREAD

**Issue by PeteSSMMSS** [JonasJoKuJonas/homeassistant-WebUntis#25]
Is it possible to grab this too via the API?

**Comment by JonasJoKuJonas** [comment]
I finally got some time to dig in to the API documentation from webuntis. 
And this is what i found:
```
getTimetableWithAbsences: Retrieves the timetable for all students 
together with absene information for a given daterange.
```
[WebUntis_JSON_RPC_API.pdf (S. 15)](https://untis-sr.ch/wp-content/uploads/2019/11/2018-09-20-WebUntis_JSON_RPC_API.pdf)

You can only get absene information from **all** users. Unfortunately this is only available for Teachers and not for Students. So this will not be implementet in the integration.
