### ISSUE TITLE
Kalender wirft Fehler 'no right for getTeachers()'

### ISSUE THREAD

**Issue by timkrueger2002** [JonasJoKuJonas/homeassistant-WebUntis#28]
Hallo Jonas, 

offenbar kann unser User in WebUntis keine Lehrerdaten abrufen:

`2022-12-12 08:56:34.156 ERROR (SyncWorker_5) [webuntis] {'jsonrpc': '2.0', 'id': '2022-12-12 08:56:33.995009', 'error': {'message': 'no right for getTeachers()', 'code': -8509}}`

Der Kalender wird zwar angelegt, ist aber leer.

**Comment by JonasJoKuJonas** [comment]
#30

**Comment by timkrueger2002** [comment]
Hallo Jonas,

der Fehler tritt leider immer noch auf:

`2022-12-14 12:32:36.818 ERROR (SyncWorker_1) [webuntis] {'jsonrpc': '2.0', 'id': '2022-12-14 12:32:36.783464', 'error': {'message': 'no right for getTeachers()', 'code': -8509}}`

Der Kalender an sich funktioniert aber.

**Comment by JonasJoKuJonas** [comment]
Kannst du mir die gesamte Fehlermeldung posten?

**Comment by JonasJoKuJonas** [comment]
Funktioniert der Kalender jetzt? (v0.3.1)

**Comment by buzz-tee** [comment]
Ok, wow, das ging jetzt fix :thumbsup:
Bei mir funktionieren jetzt die Kalender mit 0.3.1 allesamt.
Vielen Dank!
