### ISSUE TITLE
Feature Request: Stundenausfälle anzeigen

### ISSUE THREAD

**Issue by sevorl** [JonasJoKuJonas/homeassistant-WebUntis#31]
Fällt eine Stunde aus, wird diese im Untis-Stundenplan angezeigt, in dem der Text bzw. die Stunde durchgestrichen ist. 
<img width="368" alt="image" src="https://user-images.githubusercontent.com/81764300/207535029-fcaa648c-0e01-4b3c-beb6-bc750ba0ca55.png">
<img width="388" alt="image" src="https://user-images.githubusercontent.com/81764300/207535143-757878a6-5bfb-44d5-a8f0-19987e3c962a.png">

In den Screenshots sieht man, dass z.B. die erste Stunde Sport ausfällt und durch eine Vertretungsstunde Deutsch ersetzt wird. 

Es wäre schön, wenn die Kalender-Ansicht solche Ausfälle ebenfalls anzeigen kann. 
Gerne einfach mit einem zusätzlichen Text in dem abgesagten Ereignis, das ist m.E. besser als diese Termine einfach aus dem Kalender zu entfernen.

**Comment by JonasJoKuJonas** [comment]
v0.3.3
