### ISSUE TITLE
Merge calendar

### ISSUE THREAD

**Issue by SchuhManitu** [JonasJoKuJonas/homeassistant-WebUntis#32]
The calendar integration with Home Assistant works flawlessly. Thank you!
I would appreciate the possibility that you can synchronise your subjects in a Google Calendar integrated into HomeAssistant. So that the timetable is also in your normal Google calendar.

Best regards

**Comment by JonasJoKuJonas** [comment]
The WebUntis integration is a component to display your lessons in home assistant. Therefore, this feature will not be included in the integration. If you want to sync your events to your google calendar you could write a automation for that.
