### ISSUE TITLE
only show selectet subjects

### ISSUE THREAD

**Issue by NotRin7** [JonasJoKuJonas/homeassistant-WebUntis#44]
i have the problem every student has an other lesson (4 lessons parallel) plan but on web untis are listed all of tham, so my wish is to select only the subjects i have!

**Comment by JonasJoKuJonas** [comment]
Do you mean a blacklist?

**Comment by NotRin7** [comment]
Yes

**Comment by JonasJoKuJonas** [comment]
v0.4.0
