### ISSUE TITLE
how to support more than one account?

### ISSUE THREAD

**Issue by greveler** [JonasJoKuJonas/homeassistant-WebUntis#49]
Hi.

Is it possible to integrate two accounts with the same school URL (but different sets of (Username, Password) ), i. e. kid1 and kid2?

My first workaround idea was to "double" the integration using two subdirs (e. g. ".../webuntis" and ".../webuntis2") and assign different credentials to each during integration, but since there is one central repository for the configuration (.storage/core.device-* and core.config-*) this might end up in a mess.

A feature or workaround would be useful.

**Comment by Woem6** [comment]
Hey,
yes, more accounts would be great! Either if someone knew a workaround or if they could be incorporated straight away.

**Comment by JonasJoKuJonas** [comment]
I don´t really understand your problem. You can add multiple accounts by just configuring the Integration multiple times. This should work with the same URL but different username.
Or do I not understand your problem correctly?

**Comment by Woem6** [comment]
I will try that. The goal is to display multiple schedules (for my four kids...) on the dashboard.
However, I have trouble getting the integration to work, see my other post.
