### ISSUE TITLE
Stundenausfall 

### ISSUE THREAD

**Issue by niklasbaranski** [JonasJoKuJonas/homeassistant-WebUntis#50]
Guten Tag zusammen,
ich habe gesehen, dass man in der Konfiguration von HA einstellen kann, dass man ausfallende
Stunden im Kalender ausblenden kann.
![image](https://user-images.githubusercontent.com/87082036/221573805-cfd712a8-11f2-42cd-8d73-08c07a162331.png)

Leider funktioniert das bei mir nicht, da die Lehrer die Stunden nicht als "Ausfall" kennzeichnen, sondern
einfach in den Vertretungstext die Information hinzufügen, dass der Unterricht ausfällt.
![image](https://user-images.githubusercontent.com/87082036/221573489-21600458-1d84-4159-9ab6-38762b136a09.png)
![image](https://user-images.githubusercontent.com/87082036/221575199-958b9d8e-e49f-4556-b4ad-f23bbf7dd89c.png)

Es wäre also echt schön, wenn es eine Funktion gäbe sich den Vertretungstext in der json ausgeben zu lassen bzw.
wenn man es weiterführen möchte, dann die Möglichkeit geben, dass man im Vertretungstext nach Stichwörtern wie "fällt aus, Ausfall, entfällt, aufgaben im e-learning, für zuhause" sucht und diese Stunde dann als Ausfall gekennzeichnet wird.

Vielleicht ist das ja auch schon zu kompliziert gedacht und es gibt schon eine Möglichkeit, vielen Dank und mfg 
Niklas

**Comment by JonasJoKuJonas** [comment]
v0.5.0
