### ISSUE TITLE
JSON Attribute ignorieren Blacklist

### ISSUE THREAD

**Issue by Cyrelion** [JonasJoKuJonas/homeassistant-WebUntis#51]
### The problem

Hallo,

Ich habe mehrere Fächer auf der Blacklist, da ja Religion z.B. gleichzeitig ev und kath eingetragen sind, Wahlfächer ebenfalls parallel. Im Kalender der ist alles okay nur die JSON Attribute enthalten weiterhin alle Fächer, was doof ist, da ich diese ja für die Sprachausgabe nutze.

### Version of Home Assistant?

2023.2.1

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v0.4.2

**Comment by JonasJoKuJonas** [comment]
v0.5.0
