### ISSUE TITLE
Stundenplan + Alexa

### ISSUE THREAD

**Issue by Itsememario** [JonasJoKuJonas/homeassistant-WebUntis#56]
Ich habe den script gesehen in der HACS kommunity der anzeigt wie man den ganzen plan bestimmen kann aber möchte diesen nun mit alexa media player über die automatisierung nutzen.Ich kann hierführ den service notify benutzen kann auch templates benutzen da kommt nur  folgender fehler vor: JSONDecodeError: Input must be bytes, bytearray, memoryview, or str: line 1 column 1 (char 0)
könnten sie mir vill. einen code senden den ich auch benutzen könnte? LG Anton

**Comment by JonasJoKuJonas** [comment]
Welches Template nutzt du?
Hast du das generieren von JSON in den Einstellungen von der Integration aktiviert?

**Comment by Cyrelion** [comment]
Huhu, ich mach das ganze mit folgendem Block in der Message:

```
{% set lessionlist = namespace(lession=[]) %}
{% set lessionlistStandIn = namespace(lession=[]) %}
{% set lessons = states.sensor.XXXXX_next_lesson_to_wake_up.attributes.day | from_json %}
{% for lesson in lessons %}
  {% if lesson.subjects | count > 0 and lesson.code | count > 0 and lesson.code != 'cancelled' %}
    {% set lessionlist.lession = lessionlist.lession + [lesson.subjects.0.long_name] %}
  {% endif %}
  {% if lesson.original_teachers | count > 0 and lesson.code | count > 0 and lesson.code != 'cancelled' %}
    {% set lessionlistStandIn.lession = lessionlistStandIn.lession + [lesson.subjects.0.long_name] %}
  {% endif %}
{%- endfor %}


Du hast heute {%- for item in lessionlist.lession | unique %}{{ "," if not loop.last and not
    loop.first }}{{ " und" if loop.last and not loop.first }} {{item}}{%- endfor
    %}. {% if lessionlistStandIn.lession | count > 0 %} Vertretung hast du heute
    in: {%- for item in lessionlistStandIn.lession | unique %}{{ "," if not
    loop.last and not loop.first }}{{ " und" if loop.last and not loop.first }}
    {{item}}{%- endfor %}. {% endif %}
```

**Comment by JonasJoKuJonas** [comment]
Was wird dir ausgegeben, wenn du folgendes in den Template-Editor gibst?
```
{{ state_attr("sensor.NAME_next_lesson_to_wake_up", "day") }}
```

**Comment by JonasJoKuJonas** [comment]
@Itsememario hast du es mittlerweile hinbekommen?

**Comment by JonasJoKuJonas** [comment]
There hasn't been any recent activity on this issue. I will now close it. If it's still not working, please reopen it and provide further information so that I can assist you.

Thank you for your contributions.

**Comment by Itsememario** [comment]
Die Templates gehen alle nicht mehr. Ich bekomme jetzt Json Decoder error.
![Screenshot_20240217_104514_Home Assistant](https://github.com/JonasJoKuJonas/homeassistant-WebUntis/assets/90069597/a8c17cc0-1e27-452c-9fc6-538c8379466c)
