### ISSUE TITLE
Wecker

### ISSUE THREAD

**Issue by niklasbaranski** [JonasJoKuJonas/homeassistant-WebUntis#57]
Eine Möglichkeit einen Wecker zu erstellen (z.B. in IOS mit der Wecker App) welcher eine beliebige Zeit vor sensor.user_name_next_lesson_to_wake_up klingelt.

**Comment by niklasbaranski** [comment]
ja das hab ich auch schon gesehen aber da geht es mir um das synchronisieren von den Wecker aus der Wecker App mit Home Assistant. 
Meine Idee war's ja eher genau andersrum, dass man über Home Assistant einen Wecker auf seinem Handy erstellt aber das ist wahrscheinlich nicht möglich. 

Man könnte dies natürlich auch anders umsetzen, indem man quasi eine Alarm Nachricht an sein Handy sendet, die dann Krach macht.

Aber jeder, der den Wecker von Apple kennt, weiß, dass der nicht zu toppen ist  ;)

**Comment by JonasJoKuJonas** [comment]
Bei dem Blog Beitrag mit dem Android ist es so wie du es gemeint hast. Dem mit iOS hab ich wohl zu schnell überflogen.

Wie/ ob das bei iOS funktioniert kann ich die leider nicht sagen. Ich besitze nur ein Android.

**Comment by JonasJoKuJonas** [comment]
Hast du mittlerweile etwas gefunden?
Wenn ja kannst du gerne deine Lösung teilen und das Issue schließen.

**Comment by niklasbaranski** [comment]
ne leider nicht. IOS ist da relativ beschränkt..

**Comment by JonasJoKuJonas** [comment]
Kann ich dann das issue schließen?
