### ISSUE TITLE
substText im Kalender als Description anzeigen

### ISSUE THREAD

**Issue by sevorl** [JonasJoKuJonas/homeassistant-WebUntis#60]
Der Info-Text aus dem Feld substText sollte im Kalender als Description angezeigt werden.
Beispiel-Json aus dem Sensor "_next_lesson_to_wake_up":

    {
        "code": "None",
        "end": "2023-03-29 15:55:00+02:00",
        "id": 1647634,
        "klassen": [
            {
                "long_name": "Klasse xx",
                "name": "xx"
            }
        ],
        "lstext": "",
        "original_rooms": [
            {
                "long_name": "Schulsporthalle",
                "name": "SH"
            }
        ],
        "original_teachers": [
        ],
        "rooms": [
            {
                "long_name": "Klassenraum xx",
                "name": "xx"
            }
        ],
        "start": "2023-03-29 15:10:00+02:00",
        "subjects": [
            {
                "long_name": "Sport",
                "name": "SP"
            }
        ],
        "substText": "Schnupperunterricht Franz\u00f6sisch",
        "type": "ls"
    }

**Comment by JonasJoKuJonas** [comment]
v0.5.1
