### ISSUE TITLE
Backend Daten von request ausschließen

### ISSUE THREAD

**Issue by jenbob2006** [JonasJoKuJonas/homeassistant-WebUntis#61]
Moin, ich bin mir nicht sich ob das eine Fehler oder etwas anderes ist. Und zwar wenn man in den Backend Einstellungen von der Integration ist bei bei: "Daten von request ausschließen" immer teachers ausgewählt. Wenn ich es da heraus nehme und dann Speicher ist es beim nächsten mal wieder da. Das Problem, was ich denke ,dadurch entsteht ist, dass ich in den JSON nicht sehe welchen Lehrer ich habe. 
![image](https://user-images.githubusercontent.com/100792823/228580170-e8f34fea-f222-4b12-a685-4c58ae43f013.png)
![image](https://user-images.githubusercontent.com/100792823/228580461-f4bb54e8-5783-4b8d-b239-95ceffbe8cd5.png)

MFG

**Comment by JonasJoKuJonas** [comment]
Das ist kein Bug. Exclude teachers wird eingeschaltet wenn dir die Rechte fehlen auf diese Daten in der API zuzugreifen. Die Option verhindert, dass nicht jedesmal eine Fehler in den logs erscheint, wenn sich die Daten aktualisieren.

**Comment by JonasJoKuJonas** [comment]
In deinen logs müste nach dem deaktivieren "No rights for teachers" stehen
