### ISSUE TITLE
Falsches Datenformat

### ISSUE THREAD

**Issue by niklasbaranski** [JonasJoKuJonas/homeassistant-WebUntis#65]
### The problem

2023-04-27 08:00:00+02:00 Is a date not a number

### Version of Home Assistant?

Newest

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

V0.53

### Last working WebUntis version

V0.51 denke ich

### Traceback/Error logs

Error initializing 'Schule Unterricht' trigger: In 'numeric_state' condition: entity sensor.xxxx_xxxxx_next_lesson_to_wake_up state '2023-04-27 08:00:00+02:00' cannot be processed as a number

**Comment by JonasJoKuJonas** [comment]
Das Problem ist durch #55 entstanden. Du hast vergessen auch die device_calss bei WebUntisNextLessonToWakeUpSensor hinzuzufügen.
fixed in v0.5.2
