### ISSUE TITLE
Add a sensor that contains the end of the school day

### ISSUE THREAD

**Issue by aruesberg** [JonasJoKuJonas/homeassistant-WebUntis#67]
Please add a sensor to the integration that provides the end of the last hour of the current day

Purpose:
Show the time when the school is over for today. This can either be used in a dashboard or to trigger automations like heating.

Extended solution:
school_start_today & school_end_today 
The combination of start & end allow some further presence based automations concerning climate.

**Comment by JonasJoKuJonas** [comment]
will be in text update v0.5.4 (#70)
