### ISSUE TITLE
Lokalisierung für Kalenderstrings: Room Change, Cancelled

### ISSUE THREAD

**Issue by sevorl** [JonasJoKuJonas/homeassistant-WebUntis#72]
Es wäre schön, wenn "Room Change", "Cancelled" im Kalender lokalisiert/übersetzt wären und auf deutsch angezeigt werden. 

P.S: Danke für das Room Change Feature!

**Comment by JonasJoKuJonas** [comment]
I have looked around a bit but couldn't find a way to implement localization in the Calendar event, as it is handled in the Python code of the integration. If anyone knows how to obtain translations through the hass object, please let me know. If I find a solution, I will implement it immediately.

Thank you for your contributions.

For context: https://github.com/JonasJoKuJonas/homeassistant-WebUntis/blob/b8252bd9b8417c52334fe61bfa267d3814b86637/custom_components/webuntis/__init__.py#L545-L546

**Comment by sevorl** [comment]
Siehe Pull Request: https://github.com/JonasJoKuJonas/homeassistant-WebUntis/pull/149
In Verbindung mit https://github.com/JonasJoKuJonas/homeassistant-WebUntis/issues/133 wäre das gelöst
