### ISSUE TITLE
Next Class not working anymore

### ISSUE THREAD

**Issue by Cyrelion** [JonasJoKuJonas/homeassistant-WebUntis#73]
### The problem

Hi,

the next class property isn't working anymore, I think the teacher has screewed it up with an problematic entry. I get this error message in the log files:

[webuntis] {'jsonrpc': '2.0', 'id': '2023-05-31 10:04:54.013452', 'error': {'message': 'startDate and endDate are not within a single school year.', 'code': -8507}}

### Version of Home Assistant?

2023.5.4

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v0.5.4

### Traceback/Error logs

[webuntis] {'jsonrpc': '2.0', 'id': '2023-05-31 10:04:54.013452', 'error': {'message': 'startDate and endDate are not within a single school year.', 'code': -8507}}

**Comment by JonasJoKuJonas** [comment]
Could you please confirm if the issue has been resolved in v0.5.5? If it is resolved, please close the issue. If the issue is still occurring, provide additional logs for further investigation.

**Comment by Cyrelion** [comment]
Working with the new fix. Great, thank you
