### ISSUE TITLE
Invalid Credentials error but the data is definitely correct

### ISSUE THREAD

**Issue by Aaroneisele55** [JonasJoKuJonas/homeassistant-WebUntis#74]
### The problem

I get the error "invalid Credentials" even though I am sure that they are correct

### Version of Home Assistant?

2023.5.4

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v0.5.5

### Last working WebUntis version

Never worked

### Traceback/Error logs

Logger: webuntis
Source: /usr/local/lib/python3.10/site-packages/webuntis/utils/logger.py:19
First occurred: 08:02:39 (2 occurrences)
Last logged: 08:08:02

{'jsonrpc': '2.0', 'id': '2023-06-04 08:02:39.574104', 'error': {'message': 'bad credentials', 'code': -8504}}
{'jsonrpc': '2.0', 'id': '2023-06-04 08:08:02.020860', 'error': {'message': 'bad credentials', 'code': -8504}}

**Comment by JonasJoKuJonas** [comment]
When does the error happen? The error should be displayed as "Invalid username and/or password" while you are trying to log in. This can occur if your password has special characters that are not in the UTF-8 format.

**Comment by JonasJoKuJonas** [comment]
I cannot help you if you don't provide additional information. Therefore, I will close the issue. If the error persists, please reopen the issue and provide additional information and context so that I can assist you further.

Thank you for your understanding.
