### ISSUE TITLE
Fehler bei der Konfiguration der Filter

### ISSUE THREAD

**Issue by sevorl** [JonasJoKuJonas/homeassistant-WebUntis#77]
### The problem

Fehler beim Konfigurieren der Integration.

Bei der Konfiguration der Filter erscheint ein Filter

<img width="614" alt="image" src="https://github.com/JonasJoKuJonas/homeassistant-WebUntis/assets/81764300/fcafe149-6b55-4827-a194-43a8892dbebb">
<img width="700" alt="image" src="https://github.com/JonasJoKuJonas/homeassistant-WebUntis/assets/81764300/f881d9f0-df78-405c-8658-10fbf93dbb46">
<img width="514" alt="image" src="https://github.com/JonasJoKuJonas/homeassistant-WebUntis/assets/81764300/e2c7911f-3844-44db-bc0a-497ab61dada7">

### Version of Home Assistant?

2023.6

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v0.5.5

### Traceback/Error logs

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/webuntis/__init__.py:192
Integration: Web Untis (documentation, issues)
First occurred: 21:59:49 (2 occurrences)
Last logged: 22:03:19

Error setting up entry lastname_firstname_20110914 for webuntis
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/__init__.py", line 44, in async_setup_entry
    server = WebUntis(hass, unique_id, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/__init__.py", line 192, in __init__
    self.notify_entity_id = config.options["notify_entity_id"]
                            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'notify_entity_id'


### Additional information

_No response_

**Comment by JonasJoKuJonas** [comment]
Der Fehler entsteht, wenn du die aktuelle betaversion installierst ohne davor Beta gehabt zu haben. Die Beta ist experimentell und kann Fehler enthalten. Der Fehler ist mit aber bekannt und schon gefixt aber noch icht in der aktuellen Version. Beim nächsten Beta Update sollte er gefixt sein.
