### ISSUE TITLE
NullPointerException during holidays /end of school year

### ISSUE THREAD

**Issue by sevorl** [JonasJoKuJonas/homeassistant-WebUntis#79]
### The problem

Summer Holidays started in NRW, so the untis app shows "Kein aktives Schuljahr". 
This seems to cause a NPE in the integration

### Version of Home Assistant?

2023.6

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v0.5.6

### Traceback/Error logs

Logger: custom_components.webuntis
Source: custom_components/webuntis/__init__.py:199
Integration: Web Untis (documentation, issues)
First occurred: 26. Juni 2023 um 12:10:30 (1731 occurrences)
Last logged: 17:05:33

Updating the propertie is_class of 'Beispiel-Schule@Name_Vorname_01012000' failed - OSError: java.lang.NullPointerException
Updating the propertie next_class of 'Beispiel-Schule@Name_Vorname_01012000' failed - OSError: java.lang.NullPointerException
Updating the propertie next_lesson_to_wake_up of 'Beispiel-Schule@Name_Vorname_01012000' failed - OSError: java.lang.NullPointerException
Updating the propertie calendar_events of 'Beispiel-Schule@Name_Vorname_01012000' failed - OSError: java.lang.NullPointerException
Updating the propertie today-sensor of 'Beispiel-Schule@Name_Vorname_01012000' failed - OSError: java.lang.NullPointerException

**Comment by JonasJoKuJonas** [comment]
I currently have no way to reproduce the error, but I will try to fix it as soon as I have holidays and encounter the same error.
