### ISSUE TITLE
Auch für Lehrer möglich?

### ISSUE THREAD

**Issue by assineu** [JonasJoKuJonas/homeassistant-WebUntis#8]
Hallo Jonas,
ist es auch möglich, dass sich Lehrer anmelden können?

**Comment by JonasJoKuJonas** [comment]
Momentan ist das leider noch nicht möglich.
Ich werde versuchen es zu implementieren, habe aber leider keine Möglichkeit den Login zu testen da ich über keinen Lehrerzugang verfüge.

**Comment by assineu** [comment]
Also falls du jemanden brauchst zum Testen mit einem Lehrerzugang, kannst du mir gerne Bescheid geben.

**Comment by JonasJoKuJonas** [comment]
In Version v0.1.3-beta sollte es funktionieren.
Bitte kurz rückmelden ob es funktioniert.

**Comment by joe050860** [comment]
Geht - ich konnte mich einloggen - danke für die superschnelle Umsetzung

**Comment by JonasJoKuJonas** [comment]
Login für Lehrer wird im nächsten Update verfügbar sein!
Login for teachers will be available in the next update!
