### ISSUE TITLE
Change timetable source for new school year?

### ISSUE THREAD

**Issue by sevorl** [JonasJoKuJonas/homeassistant-WebUntis#83]
With the new schoolyear, I assume I have to change the time table source (from class 6 to class 7 in my case).
Is this possible in the UI without a complete new configuration from scratch or editing the file manually in /config/.storage/core.config_entries?

**Comment by JonasJoKuJonas** [comment]
Right now it is not possible but I will add this as soon as I have time

**Comment by JonasJoKuJonas** [comment]
Use personal timetable on setup (or student)
