### ISSUE TITLE
heutigen/morgigen Stundenplan in sensor

### ISSUE THREAD

**Issue by Cyrelion** [JonasJoKuJonas/homeassistant-WebUntis#9]
Hallöchen,

erstmal vielen Dank für die Implementierung, habe jetzt den Wecker unserer Tochter entsprechend automatisiert :)

Kannst du evt. noch mehr Infos z.B. über die heutigen/morgigen Stundenplan einbauen? Evt. auch einfach in den Class Entry in die Attribute?

**Comment by PeteSSMMSS** [comment]
Hey Jonas, vielen dank für diese Inetgration, läuft bei mir auch prima! Die Einbindung des Stundenplans wäre echt toll!

**Comment by sevorl** [comment]
Ein Stundenplan, bzw. eine Kalender-Integration wäre super. Unsere Schule hat leider das ical-Feature nicht lizensiert, sonst könnte man den Stundenplan einfach darüber einbinden.

**Comment by Cyrelion** [comment]
Ich hab jetzt mal die beta Version mit dem integrierten Kalender ausprobiert. Funktioniert super! Danke.

Was noch toll wäre: Einen sensor welcher die Unterrichtsstunden auflistet, welche am aktuellen Tag anstehen. Der Hintergrund ist, dass wir eine TTS Ausgabe auf dem Küchenlautsprecher haben wenn sie den Rucksack packen muss und dort könnte man super eine Ansage einbauen welche Fächer heute anstehen.

**Comment by JonasJoKuJonas** [comment]
> Einen sensor welcher die Unterrichtsstunden auflistet, welche am aktuellen Tag anstehen.

Die Funktion ist bereits in Entwicklung.

**Comment by JonasJoKuJonas** [comment]
v0.3.0

**Comment by Cyrelion** [comment]
Vielen Dank. Das Attribut sehe ich schon mal, super. Aber irgendwie kann ich nicht auf das Array zugreifen, eigentlich sollte er mir doch mit

{% set lessons = states.sensor.XXXXX_next_lesson_to_wake_up.attributes.day %}
{{ lessons[0]["start"] }}

die Start-Uhrzeit des ersten Fachs rauswerfen, es kommt aber nur

UndefinedError: 'str object' has no attribute 'start'

**Comment by JonasJoKuJonas** [comment]
Du musst das vorher noch in ein JSON object umwandeln!
Schaue mal in die [README.md](https://github.com/JonasJoKuJonas/homeassistant-WebUntis#list-lessons-from-next-day) da habe ich ein Beispiel gegeben.

**Comment by Cyrelion** [comment]
Ah, da war mein Fehler, danke. War das in der Readme vorher schon da und ich habs überlesen? ;-)

**Comment by JonasJoKuJonas** [comment]
Ich habe die readme mit dem update zur v0.3.0 aktualisiert

**Comment by Cyrelion** [comment]
Mist, aber super mitgedacht ;-)

Jetzt noch die Dupletten der Doppelstunden aussortieren und ich bin fertig. Danke nochmal fürs umsetzen!

**Comment by JonasJoKuJonas** [comment]
Wenn du ein fertiges Template hast, darfst du es auch gerne in der readme teilen!
Ich freue mich immer über Unterstützung.

**Comment by Cyrelion** [comment]
Ich kann gerne mal die Automatisierung für den "Wecker" teilen und auch mit dem Teil für die Sprachausgabe zum "losgehen" und Tasche packen.

**Comment by Cyrelion** [comment]
```
{% set lessionlist = namespace(lession=[]) %}
{% set lessons = states.sensor.isalin2009_next_lesson_to_wake_up.attributes.day | from_json %}
{% for lesson in lessons -%}
  {% set lessionlist.lession = lessionlist.lession + [lesson.subjects.0.long_name] %}
{%- endfor %}
{{ lessionlist.lession | unique | join(', ') }}
```

**Comment by Cyrelion** [comment]
Hier noch meine Automatisierungen welche ich gebaut habe:

Als erstes geht 90 Minuten (90*6) vor der ersten Stunde der Wecker bzw. in dem Beispiel hier das Kinderzimmer Deckenlist an:

`
alias: Wake Child School
description: ""
trigger:
  - platform: template
    value_template: >-
      {{ (as_timestamp(now().date() | string + 'T' + states('sensor.time') + ':00')) == (as_timestamp(states('sensor.isalin2009_next_lesson_to_wake_up')) - 90*60 ) }}
condition: []
action:
  - type: turn_on
    device_id: be8cea40ec4a07d38a2e6c096748e05f
    entity_id: light.children_room_ceiling
    domain: light
    brightness_pct: 50
mode: single
`

Danach eine zweite Automatisierung 80 Minuten vor der ersten Stunde (oder besser 10 Minuten nach dem Wecker) eine Sprachausgabe auf dem Kinderzimmer Audio welches anhand der Wetterdaten dem Kind eine kleine Anziehhilfe gibt:

`
alias: Wake Child School (Clothes)
description: ""
trigger:
  - platform: template
    value_template: >-
      {{ (as_timestamp(now().date() | string + 'T' + states('sensor.time') +
      ':00')) ==
      (as_timestamp(states('sensor.isalin2009_next_lesson_to_wake_up')) - 80*60
      ) }}
condition: []
action:
  - service: tts.cloud_say
    data:
    entity_id: media_player.children_room_homepod
    language: "de-DE"
    cache: false
    options:
      gender: "male"
    message: >-
        Guten Morgen. {% if state_attr('weather.home',
        'forecast')[0]['condition'] == "clear-night" -%}
          Heute wird es eine klare Nacht werden.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] ==
        "cloudy" -%}
          Heute wird es Wolkig werden.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] ==
        "exceptional" -%}
          Heute wird es ein außergewöhnliches Wetter werden.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] == "fog"
        -%}
          Heute wird es Nebelig werden.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] == "hail"
        -%}
          Heute wird es Hagelwetter geben.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] == "l"
        -%}
          Heute ist Blitz/Gewitter angesagt.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] ==
        "lightning-rainy" -%}
          Heute sind Blitz/Gewitter und Regen angesagt
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] ==
        "partlycloudy" -%}
          Heute wird es ein paar Wolken geben.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] ==
        "pouring" -%}
          Heute wird es in Strömen regnen.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] ==
        "rainy" -%}
          Heute wird es regnerisch werden.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] ==
        "snowy" -%}
          Heute wird es schneien.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] ==
        "snowy-rainy" -%}
          Heute wird es Schneeregen geben.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] ==
        "sunny" -%}
          Heute wird es sonnig werden.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] ==
        "windy" -%}
          Heute wird es windig werden.
        {% elif state_attr('weather.home', 'forecast')[0]['condition'] ==
        "windy-variant" -%}
          Heute wird es windig mit ein paar Wolken werden.
        {%- else -%}
          unbekannt
        {%- endif %}

        {% if state_attr('weather.home', 'forecast')[0]['temperature'] > 25 -%}
          Du solltest Shorts und Flip Flops tragen, weil es draußen heiß sein wird.
        {% elif state_attr('weather.home', 'forecast')[0]['temperature'] > 20
        -%}
          Du solltest ein Tee-Shirt und eine kurze Hose tragen, weil es draußen richtig schön sein wird.
        {% elif state_attr('weather.home', 'forecast')[0]['temperature'] > 15
        -%}
          Du solltest ein Tee-Shirt und eine Hose tragen, weil es draußen etwas kühler sein wird.
        {% elif state_attr('weather.home', 'forecast')[0]['temperature'] > 5 %}
          Du solltest eine leichte Jacke und eine Hose tragen, weil es draußen kühl sein wird.
        {%- else -%}
          Du solltest eine dickere Jacke tragen, weil es draußen richtig kalt werden wird!
        {%- endif %}

        {% if state_attr('weather.home', 'forecast')[0]['templow'] > 25 -%}
          Heute Abend solltest du eine Shorts und Flip Flops tragen, weil es draußen heiß sein wird.
        {% elif state_attr('weather.home', 'forecast')[0]['templow'] > 20 -%}
          Heute Abend solltest du ein T-Shirt und eine Hose tragen, weil es draußen kühl sein wird.
        {% elif state_attr('weather.home', 'forecast')[0]['templow'] > 15 %}
          Heute Abend solltest du eine leichte Jacke und eine Hose tragen, weil es draußen kühl sein wird.
        {%- else -%}
          Heute Abend solltest du eine dickere Jacke tragen, weil es draußen richtig kalt werden wird!
        {%- endif %}
mode: single
`

Als letztes noch das neue Script kurz bevor es zur Schule geht (40 Minuten vor der ersten Stunde):
In diesem Fall habe ich noch die Parallelfächer die Sie nicht hat entfernt.

`
alias: Wake Child School (Ready to go)
description: ""
trigger:
  - platform: template
    value_template: >-
      {{ (as_timestamp(now().date() | string + 'T' + states('sensor.time') +
      ':00')) ==
      (as_timestamp(states('sensor.isalin2009_next_lesson_to_wake_up')) - 40*60
      ) }}
condition: []
action:
  - service: tts.cloud_say
    data:
    entity_id: media_player.kitchen_homepod
    language: "de-DE"
    cache: false
    options:
      gender: "male"
    message: >-
        {% set lessionlist = namespace(lession=[]) %} {% set lessionlistStandIn = namespace(lession=[]) %}
        {% set lessons = states.sensor.isalin2009_next_lesson_to_wake_up.attributes.day | from_json %}
        {% for lesson in lessons -%}
          {% if lesson.subjects.0.long_name | string != 'Evangelische Religion' and lesson.subjects.0.long_name | string != 'Praktische Philosophie' %}
            {% set lessionlist.lession = lessionlist.lession + [lesson.subjects.0.long_name] %}
          {% endif %}
          {% if lesson.original_teachers | count > 0 %}
            {% set lessionlistStandIn.lession = lessionlistStandIn.lession + [lesson.subjects.0.long_name] %}
          {% endif %}
        {%- endfor %}
        Guten Morgen, du musst dich fertig machen. Hör bitte auf die Katzen zu streicheln und pack deinen Schulranzen.
        Du hast heute: {{ lessionlist.lession | unique | join(', ') }}.
        {% if lessionlistStandIn.lession | count > 0 %}
          Vertretung hast du heute in: {{ lessionlistStandIn.lession | unique | join(', ') }}
        {% endif %}
        Vergiss nicht deine Haare zu kämmen. Viel Spaß in der Schule.
mode: single
`


Bei Fragen, gerne fragen :)
Gruß,
Cyrelion
