### ISSUE TITLE
multiple users

### ISSUE THREAD

**Issue by Kaukasus** [JonasJoKuJonas/homeassistant-WebUntis#90]
Hi,
i would like to display different timetables for different kids on different scools.
Would be nice to see their plans.... in one view (Dashboard)

possible?

Thnx

**Comment by JonasJoKuJonas** [comment]
You can use the [atomic-calendar-revive](https://github.com/totaldebug/atomic-calendar-revive) to display multible calenders on a Dashboard. To add multible accounts simply add the integration multible times with different credentials.

You can use [atomic-calendar-revive](https://github.com/totaldebug/atomic-calendar-revive) to display multiple calendars on a dashboard. To add multiple accounts, simply add the integration multiple times with different credentials.

<img width="332" alt="image" src="https://github.com/JonasJoKuJonas/homeassistant-WebUntis/assets/86736063/6bca898e-8752-4f25-af23-aab5bc857561">
