### ISSUE TITLE
"no right for timetable" error message

### ISSUE THREAD

**Issue by derandiunddasbo** [JonasJoKuJonas/homeassistant-WebUntis#92]
When trying to configure the WebUntis integration, I'm getting this error message: 

<img width="359" alt="image" src="https://github.com/JonasJoKuJonas/homeassistant-WebUntis/assets/15999980/e1e93a16-da74-4515-8c9d-fe769dabe5b6">

```
[...]
2023-10-12 16:06:29.705 ERROR (SyncWorker_4) [webuntis] {'jsonrpc': '2.0', 'id': '2023-10-12 16:06:29.665531', 'error': {'message': 'no right for timetable', 'code': -8509}}
[...]
```

That's probably because of our school (mis-)using one WebUntis student account for the whole class and the account has no personal timetable per se. Is there anything I can do about this without trying to convince some school "admin" to change permissions for the API? (*)

Regarding the "Max, Mustermann" in the first screenshot: I'm not sure, if the correct name is mandatory for the integration to work properly. In the account's profile, the name is only declared as "Mustermann" (no first or middle name), but the integration doesn't accept only one word for the last option. Thus, I had to add something. 

<img width="1174" alt="image" src="https://github.com/JonasJoKuJonas/homeassistant-WebUntis/assets/15999980/aeb48e2a-58df-4c44-a4a3-a9a63aa67bd9">

(*) The author of the python-webuntis package states, that "...If you get no right for … you will have to ask your admin.". While I don't expect much from trying to explain some "admin" at our school, why I would need additional permissions for WebUntis, at least I'd like to know, what this means? 

Is a school admin able to configure the behaviour of the WebUntis API for this school in some Untis admin web UI? If so, is this documented somewhere, how he could do this?

**Comment by JonasJoKuJonas** [comment]
Try requesting you class timetable.
Set the timetable_source to klasse and enter the name of you class. (the name should be displayed in your untis mobile app at the top of your timetable)
in my example 12TGI
<img width="101" alt="image" src="https://github.com/JonasJoKuJonas/homeassistant-WebUntis/assets/86736063/d7112537-3d4a-4331-8734-da96ce0c60de">

let me know if it works ;)

**Comment by derandiunddasbo** [comment]
Thank you! Using the name visible in the Untis Mobile app works indeed. For me, the installation manual was a bit unclear regarding the full "name/class/..." value. Maybe you should mention in the readme that the correct value can be retrieved from the Untis Mobile app.
