### ISSUE TITLE
Unable to configure the integration

### ISSUE THREAD

**Issue by derandiunddasbo** [JonasJoKuJonas/homeassistant-WebUntis#95]
### The problem

When trying to configure the Web Untis integration (Devices & Services > Web Untis > Configure), an error message appears:

Config flow could not be loaded: {"message":"Handler does not support user"}

( or Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Handler does not support user"} in german)

Hint for other users experiencing this problem: As a workaround, the integration's config can be edited manually in the /config/.storage/core.config_entries file (requires ssh access to HAOS or the supervised installation.)

### Version of Home Assistant?

2023.11.0

### What type of installation are you running?

Home Assistant Supervised

### Version of WebUntis

1.0.1

### Last working WebUntis version

---

### Traceback/Error logs

No messages in home-assistant.log regarding this issue.

**Comment by harryweiss** [comment]
I can confirm the issue. Using the follwoing environment:

**WebUntis** Version 1.0.1

**Home Assistant**
Core 2023.11.0
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231030.1

**Comment by JonasJoKuJonas** [comment]
fixed in 1.0.2

**Comment by harryweiss** [comment]
Updated to version 1.0.2. Test passed successfully.
